-- Local stack, step 1: export production's schema from its catalog (READ-ONLY).
--
-- Why this exists: supabase/migrations/ can't rebuild the database from nothing. The first
-- 22 migrations (2026-07-04/05: the base schema, the seed catalogue) were applied before
-- the repo kept migration files, and some later ones were applied from elsewhere. With the
-- database password, `supabase db dump` is the normal route; without it, these four
-- queries read the same objects from pg_catalog and return them as statements.
--
-- Run each query on its own (Supabase SQL editor, or the MCP execute_sql tool) and save
-- each result as JSON in $LOCAL_STACK_DIR (default .claude/tmp/localstack):
--   q1.json   extensions, the admin schema, enums, sequences, tables (columns only)
--   q2.json   every function in public and admin (pg_get_functiondef)
--   q3.json   defaults, generated columns, views, constraints, indexes, triggers, the event
--             trigger, RLS, policies (public, admin, storage), the realtime publication,
--             grants (schema, table, column, function), buckets, the pgmq queue
--   data-ref.json  reference rows only (no personal data): categories, plans, support
--             settings and hours, FAQs, help guides, theme, FX, moderation lists
-- A result too long for the tool's reply is saved to a file by the harness; extract-mcp.mjs
-- turns either form into the JSON load-schema.mjs reads. Nothing here writes.
--
-- Verified 2026-10-01: loaded locally, the copy matched production on table, view,
-- function, policy, trigger, index and constraint counts, every function body (except the
-- three that load-schema.mjs repoints at local URLs), every policy expression, and every
-- table, column and function grant.

-- ── q1 ───────────────────────────────────────────────────────────────────────
set search_path = pg_catalog;
with app_ns as (select oid, nspname from pg_namespace where nspname in ('public','admin')),
stmts as (
  select 10 as o, e.extname::text as k, format('create extension if not exists %I with schema %I;', e.extname, n.nspname) as s
    from pg_extension e join pg_namespace n on n.oid=e.extnamespace where e.extname <> 'plpgsql'
  union all
  select 20, nspname::text, format('create schema if not exists %I;', nspname) from app_ns where nspname <> 'public'
  union all
  select 30, t.typname::text, format('create type %s as enum (%s);', t.oid::regtype,
      (select string_agg(quote_literal(enumlabel), ', ' order by enumsortorder) from pg_enum where enumtypid=t.oid))
    from pg_type t join app_ns n on n.oid=t.typnamespace where t.typtype='e'
  union all
  select 31, t.typname::text, format('create type %s as (%s);', t.oid::regtype,
      (select string_agg(format('%I %s', a.attname, format_type(a.atttypid, a.atttypmod)), ', ' order by a.attnum)
         from pg_attribute a where a.attrelid=t.typrelid and a.attnum>0 and not a.attisdropped))
    from pg_type t join app_ns n on n.oid=t.typnamespace join pg_class c on c.oid=t.typrelid where t.typtype='c' and c.relkind='c'
  union all
  select 32, t.typname::text, format('create domain %s as %s%s%s;', t.oid::regtype, format_type(t.typbasetype, t.typtypmod),
      case when t.typnotnull then ' not null' else '' end,
      coalesce((select ' '||string_agg(format('constraint %I %s', conname, pg_get_constraintdef(oid)), ' ') from pg_constraint where contypid=t.oid), ''))
    from pg_type t join app_ns n on n.oid=t.typnamespace where t.typtype='d'
  union all
  select 40, c.relname::text, format('create sequence if not exists %s as %s increment by %s minvalue %s maxvalue %s start with %s cache %s%s;',
      c.oid::regclass, format_type(s.seqtypid, null), s.seqincrement, s.seqmin, s.seqmax, s.seqstart, s.seqcache, case when s.seqcycle then ' cycle' else '' end)
    from pg_class c join app_ns n on n.oid=c.relnamespace join pg_sequence s on s.seqrelid=c.oid
    where c.relkind='S' and not exists (select 1 from pg_depend d where d.objid=c.oid and d.deptype='i')
  union all
  select 50, c.oid::regclass::text, format('create %stable %s (%s);', case c.relpersistence when 'u' then 'unlogged ' else '' end, c.oid::regclass,
      coalesce((select string_agg(format('%I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
          case when a.attcollation <> 0 and a.attcollation <> (select typcollation from pg_type where oid=a.atttypid)
               then ' collate '||(select format('%I.%I', cn.nspname, co.collname) from pg_collation co join pg_namespace cn on cn.oid=co.collnamespace where co.oid=a.attcollation) else '' end,
          case a.attidentity when 'a' then ' generated always as identity' when 'd' then ' generated by default as identity' else '' end,
          case when a.attnotnull then ' not null' else '' end), ', ' order by a.attnum)
        from pg_attribute a where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped and a.attgenerated=''), ''))
    from pg_class c join app_ns n on n.oid=c.relnamespace
    where c.relkind='r' and not exists (select 1 from pg_depend d where d.objid=c.oid and d.deptype='e')
)
select 'cosora-ddl-q1' as marker, json_agg(json_build_object('o', o, 'k', k, 's', s) order by o, k) as rows from stmts;

-- ── q2 ───────────────────────────────────────────────────────────────────────
set search_path = pg_catalog;
select 'cosora-ddl-q2' as marker, count(*) as n,
       json_agg(json_build_object('o', 100, 'k', p.oid::regprocedure::text, 's', pg_get_functiondef(p.oid)||';') order by p.oid::regprocedure::text) as rows
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname in ('public','admin') and p.prokind='f'
   and not exists (select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e');

-- ── q3 ───────────────────────────────────────────────────────────────────────
set search_path = pg_catalog;
with app_ns as (select oid, nspname from pg_namespace where nspname in ('public','admin')),
rels as (select c.* from pg_class c join app_ns n on n.oid=c.relnamespace where not exists (select 1 from pg_depend d where d.classid='pg_class'::regclass and d.objid=c.oid and d.deptype='e')),
funcs as (select p.* from pg_proc p join app_ns n on n.oid=p.pronamespace where p.prokind='f' and not exists (select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
rolename as (select 0::oid as oid, 'public'::text as name union all select oid, quote_ident(rolname) from pg_roles),
stmts as (
  select 110 as o, c.oid::regclass::text||'.'||a.attname as k, format('alter table %s alter column %I set default %s;', c.oid::regclass, a.attname, pg_get_expr(d.adbin, d.adrelid)) as s
    from rels c join pg_attribute a on a.attrelid=c.oid join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum
    where c.relkind='r' and a.attgenerated='' and a.attnum>0 and not a.attisdropped
  union all
  select 115, c.oid::regclass::text||'.'||a.attname, format('alter table %s add column %I %s generated always as (%s) stored;', c.oid::regclass, a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid))
    from rels c join pg_attribute a on a.attrelid=c.oid join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum
    where c.relkind='r' and a.attgenerated='s' and a.attnum>0 and not a.attisdropped
  union all
  select 118, s.relname::text, format('alter sequence %s owned by %s.%I;', s.oid::regclass, t.oid::regclass, a.attname)
    from pg_depend d join rels s on s.oid=d.objid and s.relkind='S' join pg_class t on t.oid=d.refobjid join pg_attribute a on a.attrelid=t.oid and a.attnum=d.refobjsubid
    where d.deptype='a' and d.classid='pg_class'::regclass
  union all
  select case c.relkind when 'v' then 120 else 121 end, c.oid::regclass::text,
    case c.relkind when 'v' then format('create or replace view %s%s as %s;', c.oid::regclass, case when c.reloptions is not null then ' with ('||array_to_string(c.reloptions, ', ')||')' else '' end, rtrim(pg_get_viewdef(c.oid, true), ';'))
    else format('create materialized view %s as %s with no data;', c.oid::regclass, rtrim(pg_get_viewdef(c.oid, true), ';')) end
    from rels c where c.relkind in ('v','m')
  union all
  select case con.contype when 'f' then 135 when 'c' then 131 else 130 end, con.conrelid::regclass::text||'.'||con.conname,
    format('alter table %s add constraint %I %s;', con.conrelid::regclass, con.conname, pg_get_constraintdef(con.oid))
    from pg_constraint con join rels c on c.oid=con.conrelid where con.contype in ('p','u','x','c','f')
  union all
  select 140, i.indexrelid::regclass::text, pg_get_indexdef(i.indexrelid)||';'
    from pg_index i join rels c on c.oid=i.indrelid
    where not exists (select 1 from pg_constraint con where con.conindid=i.indexrelid and con.contype in ('p','u','x'))
  union all
  select 150, t.tgrelid::regclass::text||'.'||t.tgname, pg_get_triggerdef(t.oid)||';'
    from pg_trigger t join pg_proc p on p.oid=t.tgfoid
    where not t.tgisinternal and (t.tgrelid in (select oid from rels) or p.pronamespace in (select oid from app_ns))
  union all
  select 155, e.evtname::text, format('create event trigger %I on %s%s execute function %s();', e.evtname, e.evtevent,
      case when e.evttags is not null then ' when tag in ('||array_to_string(array(select quote_literal(x) from unnest(e.evttags) x), ', ')||')' else '' end, e.evtfoid::regproc)
    from pg_event_trigger e join pg_proc p on p.oid=e.evtfoid where p.pronamespace in (select oid from app_ns)
  union all
  select 160, c.oid::regclass::text, format('alter table %s enable row level security;', c.oid::regclass) from rels c where c.relkind='r' and c.relrowsecurity
  union all
  select 161, c.oid::regclass::text, format('alter table %s force row level security;', c.oid::regclass) from rels c where c.relkind='r' and c.relforcerowsecurity
  union all
  select 165, pol.polrelid::regclass::text||'.'||pol.polname,
    format('drop policy if exists %I on %s; create policy %I on %s as %s for %s to %s%s%s;', pol.polname, pol.polrelid::regclass, pol.polname, pol.polrelid::regclass,
      case when pol.polpermissive then 'permissive' else 'restrictive' end,
      case pol.polcmd when 'r' then 'select' when 'a' then 'insert' when 'w' then 'update' when 'd' then 'delete' else 'all' end,
      (select string_agg(rn.name, ', ') from unnest(pol.polroles) r join rolename rn on rn.oid=r),
      case when pol.polqual is not null then ' using ('||pg_get_expr(pol.polqual, pol.polrelid)||')' else '' end,
      case when pol.polwithcheck is not null then ' with check ('||pg_get_expr(pol.polwithcheck, pol.polrelid)||')' else '' end)
    from pg_policy pol join pg_class c on c.oid=pol.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','admin','storage','realtime')
  union all
  select 170, c.oid::regclass::text, format('alter table %s replica identity full;', c.oid::regclass) from rels c where c.relkind='r' and c.relreplident='f'
  union all
  select 175, schemaname||'.'||tablename, format('alter publication supabase_realtime add table %I.%I;', schemaname, tablename) from pg_publication_tables where pubname='supabase_realtime'
  union all
  select 180, n.nspname::text, format('grant %s on schema %I to %s;', a.privilege_type, n.nspname, rn.name)
    from pg_namespace n cross join lateral aclexplode(coalesce(n.nspacl, acldefault('n'::"char", n.nspowner))) a join rolename rn on rn.oid=a.grantee
    where n.nspname in ('public','admin') and a.grantee <> n.nspowner
  union all
  select 185, c.oid::regclass::text, format('revoke all on %s %s from public, anon, authenticated, service_role;', case when c.relkind='S' then 'sequence' else 'table' end, c.oid::regclass)
    from rels c where c.relkind in ('r','v','m','S')
  union all
  select 186, c.oid::regclass::text||':'||a.privilege_type||':'||rn.name, format('grant %s on %s %s to %s;', a.privilege_type, case when c.relkind='S' then 'sequence' else 'table' end, c.oid::regclass, rn.name)
    from rels c cross join lateral aclexplode(coalesce(c.relacl, acldefault((case when c.relkind='S' then 's' else 'r' end)::"char", c.relowner))) a join rolename rn on rn.oid=a.grantee
    where c.relkind in ('r','v','m','S') and a.grantee <> c.relowner
  union all
  select 187, c.oid::regclass::text||'.'||att.attname||':'||a.privilege_type||':'||rn.name, format('grant %s (%I) on table %s to %s;', a.privilege_type, att.attname, c.oid::regclass, rn.name)
    from rels c join pg_attribute att on att.attrelid=c.oid and att.attacl is not null cross join lateral aclexplode(att.attacl) a join rolename rn on rn.oid=a.grantee
    where a.grantee <> c.relowner
  union all
  select 190, p.oid::regprocedure::text, format('revoke all on function %s from public, anon, authenticated, service_role;', p.oid::regprocedure) from funcs p
  union all
  select 191, p.oid::regprocedure::text||':'||rn.name, format('grant execute on function %s to %s;', p.oid::regprocedure, rn.name)
    from funcs p cross join lateral aclexplode(coalesce(p.proacl, acldefault('f'::"char", p.proowner))) a join rolename rn on rn.oid=a.grantee
    where a.grantee <> p.proowner
  union all
  select 195, b.id, format('insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values (%L, %L, %L, %s, %s) on conflict (id) do nothing;',
      b.id, b.name, b.public, coalesce(b.file_size_limit::text, 'null'), coalesce(quote_literal(b.allowed_mime_types::text)||'::text[]', 'null'))
    from storage.buckets b
  union all
  select 196, queue_name, format('select pgmq.create(%L);', queue_name) from pgmq.meta
)
select 'cosora-ddl-q3' as marker, count(*) as n, json_agg(json_build_object('o', o, 'k', k, 's', s) order by o, k) as rows from stmts;

-- ── data-ref ─────────────────────────────────────────────────────────────────
select 'cosora-data-ref' as marker, json_build_object(
 'public.categories', (select json_agg(t) from public.categories t),
 'public.pref_category_map', (select json_agg(t) from public.pref_category_map t),
 'public.subscription_plans', (select json_agg(t) from public.subscription_plans t),
 'public.support_categories', (select json_agg(t) from public.support_categories t),
 'public.support_hours', (select json_agg(t) from public.support_hours t),
 'public.support_holidays', (select json_agg(t) from public.support_holidays t),
 'public.support_settings', (select json_agg(t) from public.support_settings t),
 'public.faqs', (select json_agg(t) from public.faqs t),
 'public.help_guides', (select json_agg(t) from public.help_guides t),
 'public.site_theme', (select json_agg(t) from public.site_theme t),
 'public.fx_rates', (select json_agg(t) from public.fx_rates t),
 'admin.ad_reason_codes', (select json_agg(t) from admin.ad_reason_codes t),
 'admin.chat_block_reasons', (select json_agg(t) from admin.chat_block_reasons t),
 'admin.flag_patterns', (select json_agg(t) from admin.flag_patterns t),
 'admin.keyword_blocklist', (select json_agg(t) from admin.keyword_blocklist t),
 'admin.customer_summary_meta', (select json_agg(t) from admin.customer_summary_meta t)
) as data;
