-- Help & Support P5 content (documentation/help-content-p5.md), 2026-10-01. Needs
-- 20261001130000_faqs_seller_help_and_translations.sql first. Every insert is conditional,
-- so a database that already has a row keeps it.
--
--   1. The Hindi and Gujarati the app already shows for FAQs, copied from its catalogues
--      (src/i18n/hi.json, gu.json; the strings external-strings.json lists as FAQ text) into
--      faqs.translations. A row gets them only when both its question and its answer match.
--   2. 17 Seller Help FAQs, active, with Hindi and Gujarati.
--   3. The 7 MPF-14 replacement answers for Buyer Help, INACTIVE until launch (D-12), each just
--      after the answer it replaces (position + 5).
--   4. The four Quick Guides. "How to Complete Verification" is active; the other three
--      describe features that aren't open yet, so they're inactive.

with cat(en, hi, gu) as (values
  ($t$How do I find the right vendors for my needs?$t$, $t$मैं अपनी ज़रूरतों के लिए सही विक्रेता कैसे खोजूँ?$t$, $t$હું મારી જરૂરિયાતો માટે યોગ્ય વિક્રેતા કેવી રીતે શોધું?$t$),
  ($t$Use our smart matching system by posting your requirements. We'll connect you with verified vendors who specialize in your product category. You can also browse vendor profiles and view their ratings and reviews.$t$, $t$अपनी आवश्यकताएँ पोस्ट करके हमारी स्मार्ट मिलान व्यवस्था का उपयोग करें। हम आपको उन सत्यापित विक्रेताओं से जोड़ेंगे जो आपकी उत्पाद श्रेणी में विशेषज्ञ हैं। आप विक्रेता प्रोफ़ाइल ब्राउज़ करके उनकी रेटिंग और समीक्षाएँ भी देख सकते हैं।$t$, $t$તમારી જરૂરિયાતો પોસ્ટ કરીને અમારી સ્માર્ટ મેળ વ્યવસ્થાનો ઉપયોગ કરો. અમે તમને એવા ચકાસાયેલ વિક્રેતાઓ સાથે જોડીશું જે તમારી ઉત્પાદન શ્રેણીમાં નિષ્ણાત છે. તમે વિક્રેતા પ્રોફાઇલ બ્રાઉઝ કરીને તેમનાં રેટિંગ અને સમીક્ષાઓ પણ જોઈ શકો છો.$t$),
  ($t$How do I compare quotes from different vendors?$t$, $t$मैं अलग-अलग विक्रेताओं के कोटेशन की तुलना कैसे करूँ?$t$, $t$હું અલગ-અલગ વિક્રેતાઓના ક્વોટ્સની સરખામણી કેવી રીતે કરું?$t$),
  ($t$Go to 'My Quotes' section where you can view all received quotes side by side. Our comparison tool highlights the best price and fastest delivery options to help you make informed decisions.$t$, $t$'मेरे कोटेशन' सेक्शन में जाएँ, जहाँ आप सभी प्राप्त कोटेशन आमने-सामने देख सकते हैं। हमारा तुलना टूल सबसे अच्छी कीमत और सबसे तेज़ डिलीवरी के विकल्पों को उभारता है ताकि आप सोच-समझकर फ़ैसला ले सकें।$t$, $t$'મારા ક્વોટ્સ' વિભાગમાં જાઓ, જ્યાં તમે બધા મળેલા ક્વોટ્સ સામસામે જોઈ શકો છો. અમારું સરખામણી ટૂલ શ્રેષ્ઠ કિંમત અને સૌથી ઝડપી ડિલિવરીના વિકલ્પો દર્શાવે છે જેથી તમે સમજીને નિર્ણય લઈ શકો.$t$),
  ($t$Can I negotiate prices with vendors?$t$, $t$क्या मैं विक्रेताओं से कीमतों पर मोलभाव कर सकता हूँ?$t$, $t$શું હું વિક્રેતાઓ સાથે કિંમતો પર ભાવતાલ કરી શકું?$t$),
  ($t$Yes! You can use our integrated chat feature to communicate directly with vendors. Discuss pricing, minimum order quantities, customizations, and delivery terms before finalising your order.$t$, $t$हाँ! आप विक्रेताओं से सीधे बात करने के लिए हमारी चैट सुविधा का उपयोग कर सकते हैं। ऑर्डर पक्का करने से पहले कीमत, न्यूनतम ऑर्डर मात्रा, कस्टमाइज़ेशन और डिलीवरी की शर्तों पर चर्चा करें।$t$, $t$હા! તમે વિક્રેતાઓ સાથે સીધી વાત કરવા માટે અમારી ચેટ સુવિધાનો ઉપયોગ કરી શકો છો. ઓર્ડર પાકો કરતાં પહેલાં કિંમત, ન્યૂનતમ ઓર્ડર જથ્થો, કસ્ટમાઇઝેશન અને ડિલિવરીની શરતો પર ચર્ચા કરો.$t$),
  ($t$How do I track my order status?$t$, $t$मैं अपने ऑर्डर की स्थिति कैसे ट्रैक करूँ?$t$, $t$હું મારા ઓર્ડરની સ્થિતિ કેવી રીતે ટ્રૅક કરું?$t$),
  ($t$Once you've placed an order, you can track it from your dashboard under 'Active Orders'. You'll receive notifications at each stage — from production to shipping to delivery.$t$, $t$ऑर्डर देने के बाद आप उसे अपने डैशबोर्ड में 'Active Orders' के तहत ट्रैक कर सकते हैं। आपको हर चरण पर सूचना मिलेगी — उत्पादन से शिपिंग और डिलीवरी तक।$t$, $t$ઓર્ડર આપ્યા પછી તમે તેને તમારા ડેશબોર્ડમાં 'Active Orders' હેઠળ ટ્રૅક કરી શકો છો. તમને દરેક તબક્કે સૂચના મળશે — ઉત્પાદનથી શિપિંગ અને ડિલિવરી સુધી.$t$),
  ($t$What payment methods are accepted?$t$, $t$कौन-से भुगतान तरीके स्वीकार किए जाते हैं?$t$, $t$કઈ ચુકવણી પદ્ધતિઓ સ્વીકારાય છે?$t$),
  ($t$We support multiple payment options including bank transfers, credit/debit cards, and escrow payments for larger orders. Payment terms can be negotiated directly with vendors.$t$, $t$हम कई भुगतान विकल्प देते हैं, जिनमें बैंक ट्रांसफ़र, क्रेडिट/डेबिट कार्ड और बड़े ऑर्डर के लिए एस्क्रो भुगतान शामिल हैं। भुगतान की शर्तें सीधे विक्रेताओं से तय की जा सकती हैं।$t$, $t$અમે ઘણા ચુકવણી વિકલ્પો આપીએ છીએ, જેમાં બૅન્ક ટ્રાન્સફર, ક્રેડિટ/ડેબિટ કાર્ડ અને મોટા ઓર્ડર માટે એસ્ક્રો ચુકવણી શામેલ છે. ચુકવણીની શરતો સીધી વિક્રેતાઓ સાથે નક્કી કરી શકાય છે.$t$),
  ($t$Is my payment secure?$t$, $t$क्या मेरा भुगतान सुरक्षित है?$t$, $t$શું મારી ચુકવણી સુરક્ષિત છે?$t$),
  ($t$Yes, all transactions are secured with bank-grade encryption. For added protection, we offer escrow services where payment is released to the vendor only after you confirm receipt of goods.$t$, $t$हाँ, सभी लेन-देन बैंक-स्तर के एन्क्रिप्शन से सुरक्षित हैं। अतिरिक्त सुरक्षा के लिए हम एस्क्रो सेवा देते हैं, जिसमें भुगतान विक्रेता को तभी जारी होता है जब आप सामान मिलने की पुष्टि करते हैं।$t$, $t$હા, બધા વ્યવહારો બૅન્ક-સ્તરના એન્ક્રિપ્શનથી સુરક્ષિત છે. વધારાની સુરક્ષા માટે અમે એસ્ક્રો સેવા આપીએ છીએ, જેમાં ચુકવણી વિક્રેતાને ત્યારે જ છૂટી થાય છે જ્યારે તમે માલ મળ્યાની પુષ્ટિ કરો.$t$),
  ($t$Can I get a refund if there's an issue with my order?$t$, $t$अगर मेरे ऑर्डर में कोई समस्या हो तो क्या मुझे रिफ़ंड मिल सकता है?$t$, $t$જો મારા ઓર્ડરમાં કોઈ સમસ્યા હોય તો શું મને રિફંડ મળી શકે?$t$),
  ($t$Our buyer protection policy covers quality issues and non-delivery. Contact support within 7 days of delivery with photos/documentation of any issues to initiate a refund or replacement request.$t$, $t$हमारी खरीदार सुरक्षा नीति गुणवत्ता की समस्याओं और डिलीवरी न होने को कवर करती है। रिफ़ंड या बदलाव का अनुरोध शुरू करने के लिए डिलीवरी के 7 दिनों के भीतर किसी भी समस्या की फ़ोटो/दस्तावेज़ों के साथ सहायता से संपर्क करें।$t$, $t$અમારી ખરીદદાર સુરક્ષા નીતિ ગુણવત્તાની સમસ્યાઓ અને ડિલિવરી ન થવાને આવરી લે છે. રિફંડ કે બદલીની વિનંતી શરૂ કરવા માટે ડિલિવરીના 7 દિવસમાં કોઈપણ સમસ્યાના ફોટા/દસ્તાવેજો સાથે સપોર્ટનો સંપર્ક કરો.$t$),
  ($t$How do I update my business profile?$t$, $t$मैं अपनी बिज़नेस प्रोफ़ाइल कैसे अपडेट करूँ?$t$, $t$હું મારી બિઝનેસ પ્રોફાઇલ કેવી રીતે અપડેટ કરું?$t$),
  ($t$Go to Profile from the sidebar, then click 'Edit Profile'. You can update your company information, contact details, shipping addresses, and notification preferences.$t$, $t$साइडबार से प्रोफ़ाइल पर जाएँ, फिर 'प्रोफ़ाइल संपादित करें' पर क्लिक करें। आप अपनी कंपनी की जानकारी, संपर्क विवरण, शिपिंग पते और सूचना की पसंद अपडेट कर सकते हैं।$t$, $t$સાઇડબારમાંથી પ્રોફાઇલ પર જાઓ, પછી 'પ્રોફાઇલ સંપાદિત કરો' પર ક્લિક કરો. તમે તમારી કંપનીની માહિતી, સંપર્ક વિગતો, શિપિંગ સરનામાં અને સૂચનાની પસંદગીઓ અપડેટ કરી શકો છો.$t$),
  ($t$Can I have multiple team members on one account?$t$, $t$क्या एक खाते पर कई टीम सदस्य रह सकते हैं?$t$, $t$શું એક ખાતા પર અનેક ટીમ સભ્યો રહી શકે?$t$),
  ($t$Yes, business accounts can add team members with different permission levels. Go to Settings > Team Management to invite colleagues and assign roles.$t$, $t$हाँ, व्यवसाय खाते अलग-अलग अनुमति स्तरों वाले टीम सदस्य जोड़ सकते हैं। साथियों को आमंत्रित करने और भूमिकाएँ देने के लिए Settings > Team Management पर जाएँ।$t$, $t$હા, વ્યવસાય ખાતાં અલગ-અલગ પરવાનગી સ્તરોવાળા ટીમ સભ્યો ઉમેરી શકે છે. સાથીઓને આમંત્રિત કરવા અને ભૂમિકાઓ આપવા માટે Settings > Team Management પર જાઓ.$t$),
  ($t$Can I upgrade or downgrade my plan anytime?$t$, $t$क्या मैं कभी भी अपना प्लान अपग्रेड या डाउनग्रेड कर सकता हूँ?$t$, $t$શું હું ક્યારેય પણ મારો પ્લાન અપગ્રેડ કે ડાઉનગ્રેડ કરી શકું?$t$),
  ($t$Yes, you can upgrade your plan at any time and the difference will be prorated. Downgrades will take effect from your next billing cycle.$t$, $t$हाँ, आप कभी भी अपना प्लान अपग्रेड कर सकते हैं और अंतर की राशि आनुपातिक रूप से गिनी जाएगी। डाउनग्रेड आपके अगले बिलिंग चक्र से लागू होंगे।$t$, $t$હા, તમે ક્યારેય પણ તમારો પ્લાન અપગ્રેડ કરી શકો છો અને તફાવતની રકમ પ્રમાણસર ગણાશે. ડાઉનગ્રેડ તમારા આગલા બિલિંગ ચક્રથી લાગુ થશે.$t$),
  ($t$How do I create my first RFQ (Request for Quote)?$t$, $t$मैं अपनी पहली RFQ (कोटेशन का अनुरोध) कैसे बनाऊँ?$t$, $t$હું મારી પહેલી RFQ (ક્વોટ માટે વિનંતી) કેવી રીતે બનાવું?$t$),
  ($t$Navigate to 'Post Requirement' from your dashboard or sidebar. You can choose Quick RFQ for simple requests or create a detailed requirement with specifications like category, quantity, fabric type, and more.$t$, $t$अपने डैशबोर्ड या साइडबार से 'आवश्यकता पोस्ट करें' पर जाएँ। आप सरल अनुरोधों के लिए त्वरित RFQ चुन सकते हैं या श्रेणी, मात्रा, कपड़े के प्रकार जैसे विनिर्देशों के साथ विस्तृत आवश्यकता बना सकते हैं।$t$, $t$તમારા ડેશબોર્ડ કે સાઇડબારમાંથી 'જરૂરિયાત પોસ્ટ કરો' પર જાઓ. તમે સરળ વિનંતીઓ માટે ઝડપી RFQ પસંદ કરી શકો છો અથવા શ્રેણી, જથ્થો, કાપડનો પ્રકાર જેવાં સ્પષ્ટીકરણો સાથે વિગતવાર જરૂરિયાત બનાવી શકો છો.$t$),
  ($t$How do I change my notification settings?$t$, $t$मैं अपनी सूचना सेटिंग्स कैसे बदलूँ?$t$, $t$હું મારી સૂચના સેટિંગ્સ કેવી રીતે બદલું?$t$),
  ($t$Navigate to Profile > Notifications. You can customise which updates you receive via email, SMS, or push notifications — including quote alerts, order updates, and promotional offers.$t$, $t$प्रोफ़ाइल > सूचनाएँ पर जाएँ। आप चुन सकते हैं कि ईमेल, SMS या पुश सूचनाओं से कौन-से अपडेट मिलें — जिनमें कोटेशन अलर्ट, ऑर्डर अपडेट और प्रचार ऑफ़र शामिल हैं।$t$, $t$પ્રોફાઇલ > સૂચનાઓ પર જાઓ. તમે પસંદ કરી શકો છો કે ઇમેઇલ, SMS કે પુશ સૂચનાઓથી કયા અપડેટ્સ મળે — જેમાં ક્વોટ અલર્ટ, ઓર્ડર અપડેટ્સ અને પ્રચાર ઑફર શામેલ છે.$t$),
  ($t$How is GST handled?$t$, $t$GST कैसे लगता है?$t$, $t$GST કેવી રીતે લાગે છે?$t$),
  ($t$Plan prices are exclusive of GST; 18% GST is added at checkout. Add your GSTIN below and it's recorded on every invoice for your input tax credit.$t$, $t$प्लान की कीमतें GST के बिना हैं; चेकआउट पर 18% GST जोड़ा जाता है। नीचे अपना GSTIN जोड़ें, वह इनपुट टैक्स क्रेडिट के लिए हर इनवॉइस पर दर्ज होगा।$t$, $t$પ્લાનની કિંમતો GST વગરની છે; ચેકઆઉટ પર 18% GST ઉમેરાય છે. નીચે તમારો GSTIN ઉમેરો, તે ઇનપુટ ટૅક્સ ક્રેડિટ માટે દરેક ઇન્વૉઇસ પર નોંધાશે.$t$),
  ($t$How does billing work — is there autopay?$t$, $t$बिलिंग कैसे काम करती है — क्या ऑटोपे है?$t$, $t$બિલિંગ કેવી રીતે કામ કરે છે — શું ઑટોપે છે?$t$),
  ($t$No auto-debit. Every billing period is a discrete payment. When your period nears its end you'll get a renew reminder; if you don't renew, your account falls back to the Free plan.$t$, $t$कोई ऑटो-डेबिट नहीं। हर बिलिंग अवधि एक अलग भुगतान है। अवधि ख़त्म होने के करीब आपको नवीनीकरण की याद दिलाई जाएगी; नवीनीकरण न करने पर आपका खाता मुफ़्त प्लान पर लौट आता है।$t$, $t$કોઈ ઑટો-ડેબિટ નહીં. દરેક બિલિંગ અવધિ એક અલગ ચુકવણી છે. અવધિ પૂરી થવા આવે ત્યારે તમને નવીકરણની યાદ અપાશે; નવીકરણ ન કરો તો તમારું ખાતું મફત પ્લાન પર પાછું આવે છે.$t$),
  ($t$What payment methods do you accept?$t$, $t$आप कौन-से भुगतान तरीके स्वीकार करते हैं?$t$, $t$તમે કઈ ચુકવણી પદ્ધતિઓ સ્વીકારો છો?$t$),
  ($t$All major cards, UPI, and net banking via Razorpay. Yearly billing gives you two months free versus paying monthly.$t$, $t$Razorpay के ज़रिए सभी प्रमुख कार्ड, UPI और नेट बैंकिंग। सालाना बिलिंग पर मासिक भुगतान की तुलना में दो महीने मुफ़्त मिलते हैं।$t$, $t$Razorpay દ્વારા બધાં મુખ્ય કાર્ડ, UPI અને નેટ બૅન્કિંગ. વાર્ષિક બિલિંગમાં માસિક ચુકવણીની સરખામણીમાં બે મહિના મફત મળે છે.$t$),
  ($t$Is there a refund policy?$t$, $t$क्या रिफ़ंड नीति है?$t$, $t$શું રિફંડ નીતિ છે?$t$),
  ($t$We offer a 7-day money-back guarantee for first-time subscribers. If you're not satisfied, contact us for a full refund.$t$, $t$पहली बार सब्सक्राइब करने वालों के लिए हम 7 दिन की मनी-बैक गारंटी देते हैं। अगर आप संतुष्ट नहीं हैं, तो पूरे रिफ़ंड के लिए हमसे संपर्क करें।$t$, $t$પહેલી વાર સબ્સ્ક્રાઇબ કરનારાઓ માટે અમે 7 દિવસની મની-બૅક ગેરંટી આપીએ છીએ. જો તમે સંતુષ્ટ ન હો, તો પૂરા રિફંડ માટે અમારો સંપર્ક કરો.$t$),
  ($t$What happens when I reach my lead limit?$t$, $t$लीड सीमा पूरी होने पर क्या होता है?$t$, $t$લીડ મર્યાદા પૂરી થાય ત્યારે શું થાય છે?$t$),
  ($t$You'll receive notifications as you approach your limit. You can always upgrade your plan to get more leads or wait for the next billing cycle.$t$, $t$सीमा के करीब पहुँचने पर आपको सूचनाएँ मिलेंगी। ज़्यादा लीड के लिए आप कभी भी अपना प्लान अपग्रेड कर सकते हैं या अगले बिलिंग चक्र का इंतज़ार कर सकते हैं।$t$, $t$મર્યાદા નજીક પહોંચો ત્યારે તમને સૂચનાઓ મળશે. વધુ લીડ્સ માટે તમે ક્યારેય પણ તમારો પ્લાન અપગ્રેડ કરી શકો છો અથવા આગલા બિલિંગ ચક્રની રાહ જોઈ શકો છો.$t$),
  ($t$Do you offer discounts for annual billing?$t$, $t$क्या सालाना बिलिंग पर छूट मिलती है?$t$, $t$શું વાર્ષિક બિલિંગ પર ડિસ્કાઉન્ટ મળે છે?$t$),
  ($t$Yes! You save up to 17% when you choose annual billing. That's effectively 2 months free!$t$, $t$हाँ! सालाना बिलिंग चुनने पर आप 17% तक बचाते हैं। यानी असल में 2 महीने मुफ़्त!$t$, $t$હા! વાર્ષિક બિલિંગ પસંદ કરવાથી તમે 17% સુધી બચાવો છો. એટલે કે ખરેખર 2 મહિના મફત!$t$),
  ($t$Lowest billing plan?$t$, $t$सबसे कम बिलिंग प्लान?$t$, $t$સૌથી ઓછો બિલિંગ પ્લાન?$t$),
  ($t$Yes! Plans start at just ₹699/month (or ₹6,990/year) with Basic: 10 product listings and 150 leads a month. Just getting started? Our Free plan costs nothing and gives you 2 listings and 10 leads a month. Prices exclude GST.$t$, $t$हाँ! प्लान केवल ₹699/माह (या ₹6,990/वर्ष) से शुरू होते हैं, बेसिक में: 10 उत्पाद लिस्टिंग और हर महीने 150 लीड। अभी शुरुआत कर रहे हैं? हमारा मुफ़्त प्लान कुछ नहीं लेता और हर महीने 2 लिस्टिंग और 10 लीड देता है। कीमतों में GST शामिल नहीं है।$t$, $t$હા! પ્લાન ફક્ત ₹699/મહિનો (અથવા ₹6,990/વર્ષ)થી શરૂ થાય છે, બેઝિકમાં: 10 ઉત્પાદન લિસ્ટિંગ અને દર મહિને 150 લીડ્સ. હમણાં શરૂઆત કરો છો? અમારો મફત પ્લાન કંઈ લેતો નથી અને દર મહિને 2 લિસ્ટિંગ અને 10 લીડ્સ આપે છે. કિંમતોમાં GST શામેલ નથી.$t$),
  ($t$What is Cosora?$t$, $t$कोसोरा क्या है?$t$, $t$કોસોરા શું છે?$t$),
  ($t$Cosora is a B2B platform where manufacturers of textiles, garments, and accessories can connect directly with fashion brands, wholesalers, and retailers to generate quality leads and grow their business.$t$, $t$कोसोरा एक B2B प्लेटफ़ॉर्म है जहाँ टेक्सटाइल, परिधान और एक्सेसरीज़ के निर्माता फ़ैशन ब्रांडों, थोक विक्रेताओं और रिटेलरों से सीधे जुड़कर अच्छी लीड पा सकते हैं और अपना व्यवसाय बढ़ा सकते हैं।$t$, $t$કોસોરા એક B2B પ્લેટફોર્મ છે જ્યાં ટેક્સટાઇલ, વસ્ત્રો અને એક્સેસરીઝના ઉત્પાદકો ફૅશન બ્રાન્ડ્સ, જથ્થાબંધ વેપારીઓ અને રિટેલર સાથે સીધા જોડાઈને સારી લીડ્સ મેળવી શકે અને પોતાનો વ્યવસાય વધારી શકે.$t$),
  ($t$Who can register as a seller on Cosora?$t$, $t$कोसोरा पर विक्रेता के रूप में कौन पंजीकरण कर सकता है?$t$, $t$કોસોરા પર વિક્રેતા તરીકે કોણ નોંધણી કરી શકે?$t$),
  ($t$Manufacturers, wholesalers, exporters, or distributors of: • Fabrics & textiles • Ready-made garments • Fashion accessories (labels, tags, trims, etc.) • Anyone related to Fashion industry$t$, $t$इनके निर्माता, थोक विक्रेता, निर्यातक या वितरक:
• कपड़े और टेक्सटाइल
• रेडीमेड परिधान
• फ़ैशन एक्सेसरीज़ (लेबल, टैग, ट्रिम आदि)
• फ़ैशन उद्योग से जुड़ा कोई भी$t$, $t$આના ઉત્પાદકો, જથ્થાબંધ વેપારીઓ, નિકાસકારો કે વિતરકો:
• કાપડ અને ટેક્સટાઇલ
• રેડીમેડ વસ્ત્રો
• ફૅશન એક્સેસરીઝ (લેબલ, ટૅગ, ટ્રિમ વગેરે)
• ફૅશન ઉદ્યોગ સાથે સંકળાયેલ કોઈપણ$t$),
  ($t$Is there any cost to register?$t$, $t$क्या पंजीकरण का कोई शुल्क है?$t$, $t$શું નોંધણીની કોઈ ફી છે?$t$),
  ($t$NO, Basic registration is free. You only pay if you opt for: • Premium listings • Pay-per-lead access • Featured vendor badges$t$, $t$नहीं, बेसिक पंजीकरण मुफ़्त है। आप केवल तभी भुगतान करते हैं जब आप चुनते हैं:
• प्रीमियम लिस्टिंग
• प्रति-लीड भुगतान पहुँच
• फ़ीचर्ड विक्रेता बैज$t$, $t$ના, બેઝિક નોંધણી મફત છે. તમે ત્યારે જ ચુકવણી કરો છો જ્યારે તમે પસંદ કરો:
• પ્રીમિયમ લિસ્ટિંગ
• લીડ દીઠ ચુકવણી પ્રવેશ
• ફીચર્ડ વિક્રેતા બૅજ$t$),
  ($t$What documents are required to register?$t$, $t$पंजीकरण के लिए कौन-से दस्तावेज़ ज़रूरी हैं?$t$, $t$નોંધણી માટે કયા દસ્તાવેજો જરૂરી છે?$t$),
  ($t$• GST Certificate • PAN card • Business registration (or MSME/Udyam) • Aadhar card • Product catalog (PDF, Excel, or images)$t$, $t$• GST प्रमाणपत्र
• PAN कार्ड
• व्यवसाय पंजीकरण (या MSME/उद्यम)
• आधार कार्ड
• उत्पाद कैटलॉग (PDF, Excel या छवियाँ)$t$, $t$• GST પ્રમાણપત્ર
• PAN કાર્ડ
• વ્યવસાય નોંધણી (અથવા MSME/ઉદ્યમ)
• આધાર કાર્ડ
• ઉત્પાદન કૅટલૉગ (PDF, Excel કે છબીઓ)$t$),
  ($t$I don't have a GST number. Can I still register?$t$, $t$मेरे पास GST नंबर नहीं है। क्या मैं फिर भी पंजीकरण कर सकता हूँ?$t$, $t$મારી પાસે GST નંબર નથી. શું હું તો પણ નોંધણી કરી શકું?$t$),
  ($t$Yes, but your account will be marked as "Unverified Seller", which may affect visibility and lead access. We recommend registering your business officially.$t$, $t$हाँ, पर आपका खाता "असत्यापित विक्रेता" के रूप में मार्क होगा, जिससे दृश्यता और लीड पर असर पड़ सकता है। हम अपने व्यवसाय का आधिकारिक पंजीकरण करवाने की सलाह देते हैं।$t$, $t$હા, પણ તમારું ખાતું "અચકાસાયેલ વિક્રેતા" તરીકે ચિહ્નિત થશે, જેનાથી દૃશ્યતા અને લીડ્સ પર અસર પડી શકે. અમે તમારા વ્યવસાયની સત્તાવાર નોંધણી કરાવવાની ભલામણ કરીએ છીએ.$t$),
  ($t$How do buyers contact me?$t$, $t$खरीदार मुझसे कैसे संपर्क करते हैं?$t$, $t$ખરીદદારો મારો સંપર્ક કેવી રીતે કરે છે?$t$),
  ($t$Buyers can call or chat with you directly through the platform once your product listings are approved.$t$, $t$आपकी उत्पाद लिस्टिंग मंज़ूर होने के बाद खरीदार प्लेटफ़ॉर्म के ज़रिए आपको सीधे कॉल या चैट कर सकते हैं।$t$, $t$તમારી ઉત્પાદન લિસ્ટિંગ મંજૂર થયા પછી ખરીદદારો પ્લેટફોર્મ દ્વારા તમને સીધો કૉલ કે ચેટ કરી શકે છે.$t$),
  ($t$How are leads managed on Cosora?$t$, $t$कोसोरा पर लीड कैसे संभाली जाती हैं?$t$, $t$કોસોરા પર લીડ્સ કેવી રીતે સંભાળાય છે?$t$),
  ($t$You'll get notified via dashboard, email, or WhatsApp when a buyer is interested. In future, you can also choose pay-per-lead plans to access high-intent buyers.$t$, $t$जब कोई खरीदार रुचि दिखाता है, तो आपको डैशबोर्ड, ईमेल या WhatsApp पर सूचना मिलती है। आगे चलकर, ज़्यादा इरादे वाले खरीदारों तक पहुँचने के लिए आप प्रति-लीड भुगतान प्लान भी चुन सकेंगे।$t$, $t$જ્યારે કોઈ ખરીદદાર રસ બતાવે, ત્યારે તમને ડેશબોર્ડ, ઇમેઇલ કે WhatsApp પર સૂચના મળે છે. ભવિષ્યમાં, વધુ ઇરાદાવાળા ખરીદદારો સુધી પહોંચવા માટે તમે લીડ દીઠ ચુકવણી પ્લાન પણ પસંદ કરી શકશો.$t$),
  ($t$How long does it take to get verified?$t$, $t$सत्यापित होने में कितना समय लगता है?$t$, $t$ચકાસાવામાં કેટલો સમય લાગે છે?$t$),
  ($t$Verification usually takes 3–5 days, depending on the documents submitted.$t$, $t$सत्यापन में आमतौर पर 3–5 दिन लगते हैं, जमा किए गए दस्तावेज़ों पर निर्भर करता है।$t$, $t$ચકાસણીમાં સામાન્ય રીતે 3–5 દિવસ લાગે છે, જમા કરેલા દસ્તાવેજો પર આધાર રાખે છે.$t$),
  ($t$Do I need to ship products through Cosora?$t$, $t$क्या मुझे उत्पाद कोसोरा के ज़रिए भेजने होंगे?$t$, $t$શું મારે ઉત્પાદનો કોસોરા દ્વારા મોકલવાં પડશે?$t$),
  ($t$Not right now. Cosora helps you connect with buyers. You can handle payments and shipping directly until we integrate logistics support.$t$, $t$अभी नहीं। कोसोरा आपको खरीदारों से जोड़ने में मदद करता है। जब तक हम लॉजिस्टिक्स सहायता नहीं जोड़ते, आप भुगतान और शिपिंग सीधे संभाल सकते हैं।$t$, $t$હમણાં નહીં. કોસોરા તમને ખરીદદારો સાથે જોડવામાં મદદ કરે છે. જ્યાં સુધી અમે લૉજિસ્ટિક્સ સહાય ન જોડીએ, ત્યાં સુધી તમે ચુકવણી અને શિપિંગ સીધાં સંભાળી શકો છો.$t$),
  ($t$What information should I include in my requirement?$t$, $t$मुझे अपनी आवश्यकता में कौन-सी जानकारी देनी चाहिए?$t$, $t$મારે મારી જરૂરિયાતમાં કઈ માહિતી આપવી જોઈએ?$t$),
  ($t$Include product category, quantity, preferred fabric/material, size range, any specific designs or prints, target price range, and delivery timeline. The more details you provide, the better quotes you'll receive.$t$, $t$उत्पाद श्रेणी, मात्रा, पसंदीदा कपड़ा/सामग्री, साइज़ सीमा, कोई ख़ास डिज़ाइन या प्रिंट, लक्षित कीमत सीमा और डिलीवरी की समय-सीमा शामिल करें। आप जितना ज़्यादा विवरण देंगे, उतने बेहतर कोटेशन मिलेंगे।$t$, $t$ઉત્પાદન શ્રેણી, જથ્થો, પસંદગીનું કાપડ/સામગ્રી, સાઇઝ શ્રેણી, કોઈ ખાસ ડિઝાઇન કે પ્રિન્ટ, લક્ષ્ય કિંમત શ્રેણી અને ડિલિવરીની સમયમર્યાદા શામેલ કરો. તમે જેટલી વધુ વિગતો આપશો, તેટલા સારા ક્વોટ્સ મળશે.$t$),
  ($t$Can I edit my listings after uploading?$t$, $t$क्या अपलोड करने के बाद मैं अपनी लिस्टिंग संपादित कर सकता हूँ?$t$, $t$શું અપલોડ કર્યા પછી હું મારી લિસ્ટિંગ સંપાદિત કરી શકું?$t$),
  ($t$Yes. You can log in to your dashboard to update prices, product details, or contact information anytime.$t$, $t$हाँ। आप कभी भी अपने डैशबोर्ड में लॉग इन करके कीमतें, उत्पाद विवरण या संपर्क जानकारी अपडेट कर सकते हैं।$t$, $t$હા. તમે ક્યારેય પણ તમારા ડેશબોર્ડમાં લૉગ ઇન કરીને કિંમતો, ઉત્પાદનની વિગતો કે સંપર્ક માહિતી અપડેટ કરી શકો છો.$t$)
)
update public.faqs f
   set translations = jsonb_build_object(
         'hi', jsonb_build_object('question', q.hi, 'answer', a.hi),
         'gu', jsonb_build_object('question', q.gu, 'answer', a.gu))
  from cat q, cat a
 where q.en = f.question and a.en = f.answer and f.translations = '{}'::jsonb;

insert into public.faqs (surface, category_label, question, answer, position, active, translations)
select v.surface, v.category_label, v.question, v.answer, v.position, v.active, v.translations
  from (values
  ('seller_help', $t$KYC and verification$t$, $t$Which documents does Cosora ask for?$t$, $t$Your PAN is needed to register. On the KYC page (My Store → My Business → KYC) you can also add your GST certificate and, for a company, your CIN. Aadhaar isn't collected. Your documents are stored privately, and only Cosora's team can open them.$t$, 10, true, $t${"hi": {"question": "कोसोरा कौन-से दस्तावेज़ माँगता है?", "answer": "रजिस्टर करने के लिए आपका PAN ज़रूरी है। KYC पेज पर (मेरा स्टोर → My Business → KYC) आप अपना GST प्रमाणपत्र और कंपनी होने पर CIN भी जोड़ सकते हैं। आधार नहीं लिया जाता। आपके दस्तावेज़ निजी रूप से रखे जाते हैं, और उन्हें केवल कोसोरा की टीम खोल सकती है।"}, "gu": {"question": "કોસોરા કયા દસ્તાવેજો માગે છે?", "answer": "રજિસ્ટર કરવા માટે તમારો PAN જરૂરી છે. KYC પેજ પર (મારો સ્ટોર → My Business → KYC) તમે તમારું GST પ્રમાણપત્ર અને કંપની હોય તો CIN પણ ઉમેરી શકો છો. આધાર લેવામાં આવતું નથી. તમારા દસ્તાવેજો ખાનગી રીતે રાખવામાં આવે છે, અને ફક્ત કોસોરાની ટીમ જ તેને ખોલી શકે છે."}}$t$::jsonb),
  ('seller_help', $t$KYC and verification$t$, $t$How long does verification take?$t$, $t$Our team reviews documents within 3–5 days. You get a notification when a document is verified, or rejected with the reason.$t$, 20, true, $t${"hi": {"question": "वेरिफ़िकेशन में कितना समय लगता है?", "answer": "हमारी टीम 3–5 दिनों में दस्तावेज़ों की समीक्षा करती है। दस्तावेज़ वेरिफ़ाई होने पर, या कारण के साथ अस्वीकार होने पर, आपको सूचना मिलती है।"}, "gu": {"question": "વેરિફિકેશનમાં કેટલો સમય લાગે છે?", "answer": "અમારી ટીમ 3–5 દિવસમાં દસ્તાવેજોની સમીક્ષા કરે છે. દસ્તાવેજ વેરિફાઈ થાય, અથવા કારણ સાથે નકારવામાં આવે, ત્યારે તમને સૂચના મળે છે."}}$t$::jsonb),
  ('seller_help', $t$KYC and verification$t$, $t$My document was rejected. What now?$t$, $t$Open the KYC page and read the reason shown under the document. Upload a corrected copy, and it goes back into review. If the reason isn't clear, contact Cosora Support from Help & Support.$t$, 30, true, $t${"hi": {"question": "मेरा दस्तावेज़ अस्वीकार हो गया। अब क्या करूँ?", "answer": "KYC पेज खोलें और दस्तावेज़ के नीचे दिखाया गया कारण पढ़ें। सुधारी हुई कॉपी अपलोड करें, वह फिर से समीक्षा में जाएगी। अगर कारण साफ़ न हो, तो सहायता और समर्थन से कोसोरा सपोर्ट से संपर्क करें।"}, "gu": {"question": "મારો દસ્તાવેજ નકારવામાં આવ્યો. હવે શું કરું?", "answer": "KYC પેજ ખોલો અને દસ્તાવેજની નીચે બતાવેલું કારણ વાંચો. સુધારેલી નકલ અપલોડ કરો, તે ફરી સમીક્ષામાં જશે. જો કારણ સ્પષ્ટ ન હોય, તો મદદ અને સપોર્ટમાંથી કોસોરા સપોર્ટનો સંપર્ક કરો."}}$t$::jsonb),
  ('seller_help', $t$Leads and quotes$t$, $t$What counts as a lead?$t$, $t$A lead is a buyer's open requirement that you quote on. Each one counts once towards your plan's lead limit, however many times you revise the quote. A request a buyer sends to you directly never counts, and the limit never blocks it.$t$, 110, true, $t${"hi": {"question": "लीड किसे गिना जाता है?", "answer": "लीड किसी खरीदार की खुली आवश्यकता है जिस पर आप कोटेशन भेजते हैं। हर लीड आपके प्लान की लीड सीमा में एक बार गिनी जाती है, चाहे आप कोटेशन कितनी भी बार बदलें। कोई खरीदार सीधे आपको जो अनुरोध भेजता है, वह कभी नहीं गिना जाता, और सीमा उसे कभी नहीं रोकती।"}, "gu": {"question": "લીડ કોને ગણવામાં આવે છે?", "answer": "લીડ એટલે કોઈ ખરીદારની ખુલ્લી જરૂરિયાત જેના પર તમે ક્વોટ મોકલો છો. દરેક લીડ તમારા પ્લાનની લીડ મર્યાદામાં એક જ વાર ગણાય છે, ભલે તમે ક્વોટ કેટલી વાર બદલો. કોઈ ખરીદાર સીધી તમને જે વિનંતી મોકલે છે, તે ક્યારેય ગણાતી નથી, અને મર્યાદા તેને ક્યારેય રોકતી નથી."}}$t$::jsonb),
  ('seller_help', $t$Leads and quotes$t$, $t$What happens when I reach my lead limit?$t$, $t$You can't quote on more open requirements until your next plan period starts, or until you upgrade. Leads shows how many you've used. You can still answer requests sent to you directly.$t$, 120, true, $t${"hi": {"question": "लीड सीमा पूरी होने पर क्या होता है?", "answer": "अगली प्लान अवधि शुरू होने तक, या अपग्रेड करने तक, आप और खुली आवश्यकताओं पर कोटेशन नहीं भेज सकते। लीड्स पेज दिखाता है कि आपने कितनी इस्तेमाल की हैं। सीधे आपको भेजे गए अनुरोधों का जवाब आप फिर भी दे सकते हैं।"}, "gu": {"question": "લીડ મર્યાદા પૂરી થાય ત્યારે શું થાય છે?", "answer": "આગલો પ્લાન સમયગાળો શરૂ થાય ત્યાં સુધી, અથવા અપગ્રેડ કરો ત્યાં સુધી, તમે વધુ ખુલ્લી જરૂરિયાતો પર ક્વોટ મોકલી શકતા નથી. લીડ્સ પેજ બતાવે છે કે તમે કેટલી વાપરી છે. સીધી તમને મોકલેલી વિનંતીઓનો જવાબ તમે હજુ પણ આપી શકો છો."}}$t$::jsonb),
  ('seller_help', $t$Leads and quotes$t$, $t$Why can't I quote on a requirement?$t$, $t$A quote needs a requirement that's still open to you. The buyer may have closed it, or sent it to another seller. A suspended account can't send quotes either. If none of these applies, contact Cosora Support.$t$, 130, true, $t${"hi": {"question": "मैं किसी आवश्यकता पर कोटेशन क्यों नहीं भेज पा रहा?", "answer": "कोटेशन के लिए आवश्यकता का आपके लिए खुला होना ज़रूरी है। हो सकता है खरीदार ने उसे बंद कर दिया हो, या किसी दूसरे विक्रेता को भेजा हो। निलंबित खाता भी कोटेशन नहीं भेज सकता। अगर इनमें से कुछ भी लागू नहीं होता, तो कोसोरा सपोर्ट से संपर्क करें।"}, "gu": {"question": "હું કોઈ જરૂરિયાત પર ક્વોટ કેમ મોકલી શકતો નથી?", "answer": "ક્વોટ માટે જરૂરિયાત તમારા માટે ખુલ્લી હોવી જરૂરી છે. બની શકે કે ખરીદારે તેને બંધ કરી હોય, અથવા બીજા વિક્રેતાને મોકલી હોય. સસ્પેન્ડ કરેલું ખાતું પણ ક્વોટ મોકલી શકતું નથી. જો આમાંથી કંઈ લાગુ ન પડતું હોય, તો કોસોરા સપોર્ટનો સંપર્ક કરો."}}$t$::jsonb),
  ('seller_help', $t$Listings and videos$t$, $t$When does my product go live?$t$, $t$Every new product is reviewed before buyers see it, usually within 24–48 hours. Until then it shows as under review in My Products.$t$, 210, true, $t${"hi": {"question": "मेरा उत्पाद कब लाइव होता है?", "answer": "हर नया उत्पाद खरीदारों को दिखने से पहले समीक्षा से गुज़रता है, आम तौर पर 24–48 घंटों में। तब तक वह मेरे उत्पाद में समीक्षाधीन दिखता है।"}, "gu": {"question": "મારું ઉત્પાદન ક્યારે લાઇવ થાય છે?", "answer": "દરેક નવું ઉત્પાદન ખરીદારોને દેખાય તે પહેલાં સમીક્ષામાંથી પસાર થાય છે, સામાન્ય રીતે 24–48 કલાકમાં. ત્યાં સુધી તે મારા ઉત્પાદનોમાં સમીક્ષા હેઠળ દેખાય છે."}}$t$::jsonb),
  ('seller_help', $t$Listings and videos$t$, $t$Why did my live product disappear after I edited it?$t$, $t$Editing a live product sends it back for review, and buyers can't see it until it's approved again. It helps to make all your changes in one edit.$t$, 220, true, $t${"hi": {"question": "बदलाव करने के बाद मेरा लाइव उत्पाद क्यों छिप गया?", "answer": "लाइव उत्पाद में बदलाव करने पर वह फिर से समीक्षा में चला जाता है, और दोबारा मंज़ूरी मिलने तक खरीदार उसे नहीं देख सकते। सारे बदलाव एक ही बार में करना बेहतर है।"}, "gu": {"question": "ફેરફાર કર્યા પછી મારું લાઇવ ઉત્પાદન કેમ છુપાઈ ગયું?", "answer": "લાઇવ ઉત્પાદનમાં ફેરફાર કરવાથી તે ફરી સમીક્ષામાં જાય છે, અને ફરી મંજૂરી મળે ત્યાં સુધી ખરીદારો તેને જોઈ શકતા નથી. બધા ફેરફારો એક જ વારમાં કરવા વધુ સારું છે."}}$t$::jsonb),
  ('seller_help', $t$Listings and videos$t$, $t$What videos can I upload?$t$, $t$MP4 videos up to 50 MB and 60 seconds. iPhone .mov files aren't accepted, so export or convert them to MP4 first. Videos are reviewed, like products, before buyers see them.$t$, 230, true, $t${"hi": {"question": "मैं कौन-से वीडियो अपलोड कर सकता हूँ?", "answer": "50 MB और 60 सेकंड तक के MP4 वीडियो। iPhone की .mov फ़ाइलें स्वीकार नहीं होतीं, इसलिए पहले उन्हें MP4 में बदल लें। उत्पादों की तरह, वीडियो भी खरीदारों को दिखने से पहले समीक्षा से गुज़रते हैं।"}, "gu": {"question": "હું કયા વીડિયો અપલોડ કરી શકું?", "answer": "50 MB અને 60 સેકન્ડ સુધીના MP4 વીડિયો. iPhoneની .mov ફાઇલો સ્વીકારવામાં આવતી નથી, તેથી પહેલાં તેને MP4માં બદલો. ઉત્પાદનોની જેમ, વીડિયો પણ ખરીદારોને દેખાય તે પહેલાં સમીક્ષામાંથી પસાર થાય છે."}}$t$::jsonb),
  ('seller_help', $t$Listings and videos$t$, $t$My product or video was rejected. What can I do?$t$, $t$The reason is shown on the item and in your notifications. Fix what it names and submit it again, and it goes back into review.$t$, 240, true, $t${"hi": {"question": "मेरा उत्पाद या वीडियो अस्वीकार हो गया। मैं क्या करूँ?", "answer": "कारण उस आइटम पर और आपकी सूचनाओं में दिखता है। बताई गई बात ठीक करें और फिर से जमा करें, वह दोबारा समीक्षा में जाएगा।"}, "gu": {"question": "મારું ઉત્પાદન કે વીડિયો નકારવામાં આવ્યો. હું શું કરું?", "answer": "કારણ તે આઇટમ પર અને તમારી સૂચનાઓમાં દેખાય છે. જણાવેલી બાબત સુધારો અને ફરી સબમિટ કરો, તે ફરી સમીક્ષામાં જશે."}}$t$::jsonb),
  ('seller_help', $t$Advertising$t$, $t$When does my ad campaign start?$t$, $t$After payment, Cosora reviews every campaign before it can show to buyers. Once approved, it starts on its start date. If we need changes, you'll see the reason on the campaign.$t$, 310, true, $t${"hi": {"question": "मेरा विज्ञापन अभियान कब शुरू होता है?", "answer": "भुगतान के बाद, खरीदारों को दिखने से पहले कोसोरा हर अभियान की समीक्षा करता है। मंज़ूरी मिलने पर वह अपनी शुरुआती तारीख़ से शुरू होता है। अगर बदलाव चाहिए, तो कारण आपको अभियान पर दिखेगा।"}, "gu": {"question": "મારું જાહેરાત અભિયાન ક્યારે શરૂ થાય છે?", "answer": "ચુકવણી પછી, ખરીદારોને દેખાય તે પહેલાં કોસોરા દરેક અભિયાનની સમીક્ષા કરે છે. મંજૂરી મળ્યા પછી તે તેની શરૂઆતની તારીખથી શરૂ થાય છે. જો ફેરફાર જોઈએ, તો કારણ તમને અભિયાન પર દેખાશે."}}$t$::jsonb),
  ('seller_help', $t$Advertising$t$, $t$Why was my campaign paused or rejected?$t$, $t$Cosora pauses or rejects a campaign that breaks the ad rules, for example with a misleading claim. The reason appears on the campaign in Advertisements. Fix it and submit it again, or contact Cosora Support if the reason isn't clear.$t$, 320, true, $t${"hi": {"question": "मेरा अभियान रोका या अस्वीकार क्यों किया गया?", "answer": "जो अभियान विज्ञापन नियम तोड़ता है, जैसे कोई भ्रामक दावा, उसे कोसोरा रोकता या अस्वीकार करता है। कारण विज्ञापन पेज में अभियान पर दिखता है। उसे ठीक करके फिर से जमा करें, या कारण साफ़ न हो तो कोसोरा सपोर्ट से संपर्क करें।"}, "gu": {"question": "મારું અભિયાન કેમ રોકવામાં કે નકારવામાં આવ્યું?", "answer": "જે અભિયાન જાહેરાતના નિયમો તોડે, જેમ કે કોઈ ભ્રામક દાવો, તેને કોસોરા રોકે છે કે નકારે છે. કારણ જાહેરાતો પેજમાં અભિયાન પર દેખાય છે. તેને સુધારીને ફરી સબમિટ કરો, અથવા કારણ સ્પષ્ટ ન હોય તો કોસોરા સપોર્ટનો સંપર્ક કરો."}}$t$::jsonb),
  ('seller_help', $t$Plans and billing$t$, $t$Does my plan renew by itself?$t$, $t$No. Each month or year is a one-time payment that you make yourself. If a period ends without a new payment, your account goes back to the Free plan and its limits.$t$, 410, true, $t${"hi": {"question": "क्या मेरा प्लान अपने-आप रिन्यू होता है?", "answer": "नहीं। हर महीना या साल एक बार का भुगतान है जो आप खुद करते हैं। अगर नया भुगतान किए बिना अवधि खत्म हो जाती है, तो आपका खाता मुफ़्त प्लान और उसकी सीमाओं पर लौट आता है।"}, "gu": {"question": "શું મારો પ્લાન આપમેળે રિન્યૂ થાય છે?", "answer": "ના. દરેક મહિનો કે વર્ષ એક વખતની ચુકવણી છે જે તમે જાતે કરો છો. જો નવી ચુકવણી વિના સમયગાળો પૂરો થાય, તો તમારું ખાતું મફત પ્લાન અને તેની મર્યાદાઓ પર પાછું આવે છે."}}$t$::jsonb),
  ('seller_help', $t$Plans and billing$t$, $t$Where are my invoices?$t$, $t$My Payments lists your subscription and advertising payments, each with its invoice. Add your GSTIN on the Subscription page, and it's recorded on your invoices.$t$, 420, true, $t${"hi": {"question": "मेरे इनवॉइस कहाँ हैं?", "answer": "मेरे भुगतान में आपके सब्सक्रिप्शन और विज्ञापन के भुगतान, हर एक अपने इनवॉइस के साथ, दिखते हैं। सब्सक्रिप्शन पेज पर अपना GSTIN जोड़ें, वह आपके इनवॉइस पर दर्ज होगा।"}, "gu": {"question": "મારા ઇન્વૉઇસ ક્યાં છે?", "answer": "મારી ચુકવણીઓમાં તમારી સબ્સ્ક્રિપ્શન અને જાહેરાતની ચુકવણીઓ, દરેક તેના ઇન્વૉઇસ સાથે, દેખાય છે. સબ્સ્ક્રિપ્શન પેજ પર તમારો GSTIN ઉમેરો, તે તમારા ઇન્વૉઇસ પર નોંધાશે."}}$t$::jsonb),
  ('seller_help', $t$Account and suspension$t$, $t$What happens if my account is suspended?$t$, $t$You stay signed in, and what's already live stays up. But you can't add products, videos, quotes, requirements, campaigns or reviews, and your campaigns stop showing to buyers. You get a notification when it happens.$t$, 510, true, $t${"hi": {"question": "मेरा खाता निलंबित होने पर क्या होता है?", "answer": "आप साइन इन रहते हैं, और जो पहले से लाइव है वह बना रहता है। लेकिन आप उत्पाद, वीडियो, कोटेशन, आवश्यकताएँ, अभियान या समीक्षाएँ नहीं जोड़ सकते, और आपके अभियान खरीदारों को दिखना बंद हो जाते हैं। ऐसा होने पर आपको सूचना मिलती है।"}, "gu": {"question": "મારું ખાતું સસ્પેન્ડ થાય તો શું થાય છે?", "answer": "તમે સાઇન ઇન રહો છો, અને જે પહેલેથી લાઇવ છે તે ચાલુ રહે છે. પરંતુ તમે ઉત્પાદનો, વીડિયો, ક્વોટ્સ, જરૂરિયાતો, અભિયાનો કે સમીક્ષાઓ ઉમેરી શકતા નથી, અને તમારાં અભિયાનો ખરીદારોને દેખાવાનું બંધ થાય છે. આવું થાય ત્યારે તમને સૂચના મળે છે."}}$t$::jsonb),
  ('seller_help', $t$Account and suspension$t$, $t$How do I appeal a suspension?$t$, $t$Contact Cosora Support from Help & Support: a suspended account can still reach us. Give your store name and tell us why you think the suspension is wrong, and the team will review it.$t$, 520, true, $t${"hi": {"question": "निलंबन के खिलाफ़ अपील कैसे करूँ?", "answer": "सहायता और समर्थन से कोसोरा सपोर्ट से संपर्क करें: निलंबित खाता भी हम तक पहुँच सकता है। अपने स्टोर का नाम बताएँ और यह भी कि आपको निलंबन गलत क्यों लगता है, टीम उसकी समीक्षा करेगी।"}, "gu": {"question": "સસ્પેન્શન સામે અપીલ કેવી રીતે કરું?", "answer": "મદદ અને સપોર્ટમાંથી કોસોરા સપોર્ટનો સંપર્ક કરો: સસ્પેન્ડ કરેલું ખાતું પણ અમારા સુધી પહોંચી શકે છે. તમારા સ્ટોરનું નામ જણાવો અને તમને સસ્પેન્શન ખોટું કેમ લાગે છે તે પણ, ટીમ તેની સમીક્ષા કરશે."}}$t$::jsonb),
  ('seller_help', $t$Account and suspension$t$, $t$Can I buy and sell from one account?$t$, $t$Yes. One account can buy and sell. Use the buyer and seller switch at the top of the app to change sides; your store, leads and plan stay as they are.$t$, 530, true, $t${"hi": {"question": "क्या मैं एक ही खाते से खरीद और बेच सकता हूँ?", "answer": "हाँ। एक खाते से खरीदना और बेचना, दोनों हो सकते हैं। ऐप के ऊपर खरीदार और विक्रेता वाले स्विच से तरफ़ बदलें; आपका स्टोर, लीड्स और प्लान वैसे ही रहते हैं।"}, "gu": {"question": "શું હું એક જ ખાતાથી ખરીદી અને વેચાણ કરી શકું?", "answer": "હા. એક ખાતાથી ખરીદી અને વેચાણ બંને થઈ શકે છે. ઍપની ઉપર ખરીદાર અને વિક્રેતા સ્વિચથી બાજુ બદલો; તમારો સ્ટોર, લીડ્સ અને પ્લાન એમ જ રહે છે."}}$t$::jsonb)
  ) as v(surface, category_label, question, answer, position, active, translations)
 where not exists (select 1 from public.faqs f where f.surface = v.surface and f.question = v.question);

insert into public.faqs (surface, category_label, question, answer, position, active, translations)
select v.surface, v.category_label, v.question, v.answer, v.position, v.active, v.translations
  from (values
  ('buyer_help', $t$Orders & Quotes$t$, $t$How do I keep track of my requirements and quotes?$t$, $t$Cosora doesn't handle orders or deliveries: you agree those with the vendor directly. Your requirements and the quotes on them are in My Quotes, and your conversations with vendors are in Messages.$t$, 135, false, $t${"hi": {"question": "मैं अपनी आवश्यकताओं और कोटेशन पर नज़र कैसे रखूँ?", "answer": "कोसोरा ऑर्डर या डिलीवरी नहीं संभालता: वह आप सीधे विक्रेता के साथ तय करते हैं। आपकी आवश्यकताएँ और उन पर आए कोटेशन मेरे कोटेशन में हैं, और विक्रेताओं से आपकी बातचीत संदेश में है।"}, "gu": {"question": "હું મારી જરૂરિયાતો અને ક્વોટ્સ પર નજર કેવી રીતે રાખું?", "answer": "કોસોરા ઑર્ડર કે ડિલિવરી સંભાળતું નથી: તે તમે સીધા વિક્રેતા સાથે નક્કી કરો છો. તમારી જરૂરિયાતો અને તેના પરના ક્વોટ્સ મારા ક્વોટ્સમાં છે, અને વિક્રેતાઓ સાથેની તમારી વાતચીત સંદેશામાં છે."}}$t$::jsonb),
  ('buyer_help', $t$Payments & Billing$t$, $t$How do I pay a vendor?$t$, $t$You pay the vendor directly, on terms you agree with them, for example by bank transfer against their invoice. Cosora doesn't take payment for orders, and never asks you to pay a vendor through Cosora.$t$, 215, false, $t${"hi": {"question": "मैं विक्रेता को भुगतान कैसे करूँ?", "answer": "आप सीधे विक्रेता को, उनके साथ तय की गई शर्तों पर भुगतान करते हैं, जैसे उनके इनवॉइस पर बैंक ट्रांसफ़र से। कोसोरा ऑर्डर का भुगतान नहीं लेता, और कभी नहीं कहता कि आप विक्रेता को कोसोरा के ज़रिए भुगतान करें।"}, "gu": {"question": "હું વિક્રેતાને ચુકવણી કેવી રીતે કરું?", "answer": "તમે સીધા વિક્રેતાને, તેમની સાથે નક્કી કરેલી શરતો પર ચુકવણી કરો છો, જેમ કે તેમના ઇન્વૉઇસ સામે બેંક ટ્રાન્સફરથી. કોસોરા ઑર્ડરની ચુકવણી લેતું નથી, અને ક્યારેય નથી કહેતું કે તમે વિક્રેતાને કોસોરા મારફતે ચુકવણી કરો."}}$t$::jsonb),
  ('buyer_help', $t$Payments & Billing$t$, $t$How do I pay a vendor safely?$t$, $t$Before paying, check the vendor's profile and verification badge, ask for a written quote or proforma invoice with their GSTIN, and pay the business account named on it. Be careful if you're asked to pay a personal account or to move off Cosora in a hurry. If something feels wrong, use Report fraud in Help & Support.$t$, 225, false, $t${"hi": {"question": "विक्रेता को सुरक्षित तरीके से भुगतान कैसे करूँ?", "answer": "भुगतान से पहले विक्रेता की प्रोफ़ाइल और वेरिफ़िकेशन बैज देखें, उनके GSTIN के साथ लिखित कोटेशन या प्रोफ़ॉर्मा इनवॉइस माँगें, और उस पर लिखे व्यवसाय खाते में ही भुगतान करें। अगर आपसे निजी खाते में भुगतान करने या जल्दबाज़ी में कोसोरा छोड़ने को कहा जाए, तो सावधान रहें। कुछ गलत लगे, तो सहायता और समर्थन में धोखाधड़ी की रिपोर्ट करें।"}, "gu": {"question": "વિક્રેતાને સુરક્ષિત રીતે ચુકવણી કેવી રીતે કરું?", "answer": "ચુકવણી પહેલાં વિક્રેતાની પ્રોફાઇલ અને વેરિફિકેશન બેજ જુઓ, તેમના GSTIN સાથે લેખિત ક્વોટ કે પ્રોફોર્મા ઇન્વૉઇસ માગો, અને તેના પર લખેલા વ્યવસાય ખાતામાં જ ચુકવણી કરો. જો તમને ખાનગી ખાતામાં ચુકવણી કરવા કે ઉતાવળમાં કોસોરા છોડવા કહેવામાં આવે, તો સાવધાન રહો. કંઈ ખોટું લાગે, તો મદદ અને સપોર્ટમાં છેતરપિંડીની જાણ કરો."}}$t$::jsonb),
  ('buyer_help', $t$Payments & Billing$t$, $t$What if there's a problem with my order?$t$, $t$Orders are between you and the vendor, so start by raising it with them in Messages. Cosora can't refund an order it didn't take payment for. If the vendor stops responding, or you think it's fraud, report it from Help & Support and our team will review it.$t$, 235, false, $t${"hi": {"question": "अगर मेरे ऑर्डर में कोई समस्या हो तो?", "answer": "ऑर्डर आपके और विक्रेता के बीच होते हैं, इसलिए पहले संदेश में उनसे बात करें। कोसोरा उस ऑर्डर का रिफ़ंड नहीं दे सकता जिसका भुगतान उसने लिया ही नहीं। अगर विक्रेता जवाब देना बंद कर दे, या आपको धोखाधड़ी लगे, तो सहायता और समर्थन से रिपोर्ट करें, हमारी टीम उसकी समीक्षा करेगी।"}, "gu": {"question": "જો મારા ઑર્ડરમાં કોઈ સમસ્યા હોય તો?", "answer": "ઑર્ડર તમારા અને વિક્રેતા વચ્ચે હોય છે, તેથી પહેલાં સંદેશામાં તેમની સાથે વાત કરો. કોસોરા એવા ઑર્ડરનું રિફંડ આપી શકતું નથી જેની ચુકવણી તેણે લીધી જ નથી. જો વિક્રેતા જવાબ આપવાનું બંધ કરે, અથવા તમને છેતરપિંડી લાગે, તો મદદ અને સપોર્ટમાંથી જાણ કરો, અમારી ટીમ તેની સમીક્ષા કરશે."}}$t$::jsonb),
  ('buyer_help', $t$Account Management$t$, $t$How do I update my profile?$t$, $t$Open Profile. Edit Profile changes your photo and personal details, and Business Details holds your business name, address, GSTIN and PAN.$t$, 315, false, $t${"hi": {"question": "मैं अपनी प्रोफ़ाइल कैसे अपडेट करूँ?", "answer": "प्रोफ़ाइल खोलें। प्रोफ़ाइल संपादित करें से आपकी फ़ोटो और निजी विवरण बदलते हैं, और व्यवसाय विवरण में आपके व्यवसाय का नाम, पता, GSTIN और PAN हैं।"}, "gu": {"question": "હું મારી પ્રોફાઇલ કેવી રીતે અપડેટ કરું?", "answer": "પ્રોફાઇલ ખોલો. પ્રોફાઇલ સંપાદિત કરોથી તમારો ફોટો અને અંગત વિગતો બદલાય છે, અને વ્યવસાય વિગતોમાં તમારા વ્યવસાયનું નામ, સરનામું, GSTIN અને PAN છે."}}$t$::jsonb),
  ('buyer_help', $t$Account Management$t$, $t$Can I have multiple team members on one account?$t$, $t$Not at the moment. Each account belongs to one person and signs in with one mobile number.$t$, 325, false, $t${"hi": {"question": "क्या एक खाते में कई टीम सदस्य हो सकते हैं?", "answer": "अभी नहीं। हर खाता एक व्यक्ति का होता है और एक मोबाइल नंबर से साइन इन होता है।"}, "gu": {"question": "શું એક ખાતામાં ઘણા ટીમ સભ્યો હોઈ શકે?", "answer": "હાલમાં નહીં. દરેક ખાતું એક વ્યક્તિનું હોય છે અને એક મોબાઇલ નંબરથી સાઇન ઇન થાય છે."}}$t$::jsonb),
  ('buyer_help', $t$Account Management$t$, $t$How do I change my notification settings?$t$, $t$Profile → Notifications saves your preferences. Today Cosora shows updates in the app only, under the bell. It doesn't send email, SMS or push messages yet.$t$, 335, false, $t${"hi": {"question": "मैं अपनी सूचना सेटिंग्स कैसे बदलूँ?", "answer": "प्रोफ़ाइल → सूचनाएँ में आपकी पसंद सेव होती है। अभी कोसोरा अपडेट केवल ऐप में, घंटी के नीचे दिखाता है। ईमेल, SMS या पुश संदेश अभी नहीं भेजे जाते।"}, "gu": {"question": "હું મારી સૂચના સેટિંગ્સ કેવી રીતે બદલું?", "answer": "પ્રોફાઇલ → સૂચનાઓમાં તમારી પસંદગી સેવ થાય છે. હાલમાં કોસોરા અપડેટ ફક્ત ઍપમાં, ઘંટડી નીચે બતાવે છે. ઈમેલ, SMS કે પુશ સંદેશા હજુ મોકલવામાં આવતા નથી."}}$t$::jsonb)
  ) as v(surface, category_label, question, answer, position, active, translations)
 where not exists (select 1 from public.faqs f where f.surface = v.surface and f.question = v.question and f.answer = v.answer);

insert into public.help_guides (slug, audience, title, body, position, active)
values
  ($t$complete-verification$t$, $t$vendor$t$, $t${"en": "How to Complete Verification", "hi": "वेरिफ़िकेशन कैसे पूरा करें", "gu": "વેરિફિકેશન કેવી રીતે પૂરું કરવું"}$t$::jsonb, $t${"en": "Open My Store, then My Business, then KYC.\nUpload your PAN card. Add your GST certificate, and your CIN if you're a company.\nCheck that each file is clear and readable, then submit it.\nOur team reviews documents within 3–5 days, and you get a notification for each decision.\nIf a document is rejected, read the reason under it and upload a corrected copy. It goes back into review.", "hi": "मेरा स्टोर खोलें, फिर My Business, फिर KYC।\nअपना PAN कार्ड अपलोड करें। अपना GST प्रमाणपत्र, और कंपनी होने पर CIN भी जोड़ें।\nदेख लें कि हर फ़ाइल साफ़ और पढ़ने लायक है, फिर उसे जमा करें।\nहमारी टीम 3–5 दिनों में दस्तावेज़ों की समीक्षा करती है, और हर फ़ैसले पर आपको सूचना मिलती है।\nअगर कोई दस्तावेज़ अस्वीकार हो, तो उसके नीचे लिखा कारण पढ़ें और सुधारी हुई कॉपी अपलोड करें। वह फिर से समीक्षा में जाएगा।", "gu": "મારો સ્ટોર ખોલો, પછી My Business, પછી KYC.\nતમારું PAN કાર્ડ અપલોડ કરો. તમારું GST પ્રમાણપત્ર, અને કંપની હોય તો CIN પણ ઉમેરો.\nદરેક ફાઇલ સ્પષ્ટ અને વાંચી શકાય તેવી છે તે જોઈ લો, પછી સબમિટ કરો.\nઅમારી ટીમ 3–5 દિવસમાં દસ્તાવેજોની સમીક્ષા કરે છે, અને દરેક નિર્ણય પર તમને સૂચના મળે છે.\nજો કોઈ દસ્તાવેજ નકારવામાં આવે, તો તેની નીચે લખેલું કારણ વાંચો અને સુધારેલી નકલ અપલોડ કરો. તે ફરી સમીક્ષામાં જશે."}$t$::jsonb, 10, true),
  ($t$request-a-callback$t$, $t$both$t$, $t${"en": "Request a Callback", "hi": "कॉलबैक का अनुरोध करें", "gu": "કૉલબેકની વિનંતી કરો"}$t$::jsonb, $t${"en": "Open Help & Support and choose Request a callback.\nPick what it's about, and check the number we should call.\nChoose a one-hour time inside support hours: Monday to Friday, 10:00–19:00 IST.\nWe call you in that hour. If we can't reach you, My requests says so, and you can book another time.\nNeed us sooner? Call +91 88155 78226 during support hours.", "hi": "सहायता और समर्थन खोलें और कॉलबैक का अनुरोध करें चुनें।\nविषय चुनें, और वह नंबर जाँच लें जिस पर हमें कॉल करना है।\nसपोर्ट के समय में एक घंटे का समय चुनें: सोमवार से शुक्रवार, 10:00–19:00 IST।\nहम उसी घंटे में आपको कॉल करते हैं। अगर हम आप तक न पहुँच पाएँ, तो मेरे अनुरोध में यह दिखेगा, और आप दूसरा समय चुन सकते हैं।\nजल्दी बात करनी है? सपोर्ट के समय में +91 88155 78226 पर कॉल करें।", "gu": "મદદ અને સપોર્ટ ખોલો અને કૉલબેકની વિનંતી કરો પસંદ કરો.\nવિષય પસંદ કરો, અને જે નંબર પર અમારે કૉલ કરવાનો છે તે તપાસી લો.\nસપોર્ટના સમયમાં એક કલાકનો સમય પસંદ કરો: સોમવારથી શુક્રવાર, 10:00–19:00 IST.\nઅમે તે જ કલાકમાં તમને કૉલ કરીએ છીએ. જો અમે તમારો સંપર્ક ન કરી શકીએ, તો મારી વિનંતીઓમાં તે દેખાશે, અને તમે બીજો સમય પસંદ કરી શકો છો.\nવહેલી વાત કરવી છે? સપોર્ટના સમયમાં +91 88155 78226 પર કૉલ કરો."}$t$::jsonb, 20, false),
  ($t$audio-pdf-image-support$t$, $t$both$t$, $t${"en": "Audio, PDF & Image Support", "hi": "ऑडियो, PDF और फ़ोटो भेजना", "gu": "ઑડિયો, PDF અને ફોટો મોકલવા"}$t$::jsonb, $t${"en": "In a chat with Cosora Support, tap Attach to add a photo or a PDF.\nPhotos (JPG, PNG or WebP) and voice notes can be up to 5 MB each, PDFs up to 10 MB, and a message can carry up to 5 files.\nTo send a voice note, hold the microphone, speak for up to 2 minutes, and let go.\nIf your phone blocks the microphone, choose an audio file instead.\nOnly you and Cosora's team can open the files in your request.", "hi": "कोसोरा सपोर्ट के साथ चैट में, फ़ोटो या PDF जोड़ने के लिए अटैच करें पर टैप करें।\nफ़ोटो (JPG, PNG या WebP) और वॉइस नोट हर एक 5 MB तक, PDF 10 MB तक हो सकते हैं, और एक संदेश में 5 फ़ाइलें तक जा सकती हैं।\nवॉइस नोट भेजने के लिए माइक्रोफ़ोन दबाकर रखें, 2 मिनट तक बोलें, और छोड़ दें।\nअगर आपका फ़ोन माइक्रोफ़ोन रोकता है, तो उसकी जगह कोई ऑडियो फ़ाइल चुनें।\nआपके अनुरोध की फ़ाइलें केवल आप और कोसोरा की टीम खोल सकती है।", "gu": "કોસોરા સપોર્ટ સાથેની ચેટમાં, ફોટો કે PDF ઉમેરવા જોડો પર ટૅપ કરો.\nફોટો (JPG, PNG કે WebP) અને વૉઇસ નોટ દરેક 5 MB સુધી, PDF 10 MB સુધી હોઈ શકે, અને એક સંદેશામાં 5 ફાઇલો સુધી જઈ શકે.\nવૉઇસ નોટ મોકલવા માઇક્રોફોન દબાવી રાખો, 2 મિનિટ સુધી બોલો, અને છોડી દો.\nજો તમારો ફોન માઇક્રોફોન રોકે, તો તેને બદલે કોઈ ઑડિયો ફાઇલ પસંદ કરો.\nતમારી વિનંતીની ફાઇલો ફક્ત તમે અને કોસોરાની ટીમ જ ખોલી શકે છે."}$t$::jsonb, 30, false),
  ($t$payment-and-subscription$t$, $t$vendor$t$, $t${"en": "Payment & Subscription Guide", "hi": "भुगतान और सब्सक्रिप्शन गाइड", "gu": "ચુકવણી અને સબ્સ્ક્રિપ્શન માર્ગદર્શિકા"}$t$::jsonb, $t${"en": "Open Subscription to compare the plans and their product and lead limits.\nChoose monthly or yearly. A year costs ten times the monthly price.\nGST at 18% is added at checkout. Add your GSTIN first, so it's recorded on your invoices.\nEach period is a one-time payment. Nothing renews automatically.\nYour invoices are in My Payments.\nWhen a paid period ends, your account returns to the Free plan's limits until you pay for another.", "hi": "प्लान और उनकी उत्पाद व लीड सीमाओं की तुलना के लिए सब्सक्रिप्शन खोलें।\nमासिक या वार्षिक चुनें। एक साल की कीमत मासिक कीमत की दस गुना है।\nचेकआउट पर 18% GST जुड़ता है। पहले अपना GSTIN जोड़ें, ताकि वह आपके इनवॉइस पर दर्ज हो।\nहर अवधि एक बार का भुगतान है। कुछ भी अपने-आप रिन्यू नहीं होता।\nआपके इनवॉइस मेरे भुगतान में हैं।\nभुगतान वाली अवधि खत्म होने पर, अगली अवधि का भुगतान करने तक आपका खाता मुफ़्त प्लान की सीमाओं पर लौट आता है।", "gu": "પ્લાન અને તેની ઉત્પાદન તથા લીડ મર્યાદાઓની તુલના માટે સબ્સ્ક્રિપ્શન ખોલો.\nમાસિક કે વાર્ષિક પસંદ કરો. એક વર્ષની કિંમત માસિક કિંમતથી દસ ગણી છે.\nચેકઆઉટ વખતે 18% GST ઉમેરાય છે. પહેલાં તમારો GSTIN ઉમેરો, જેથી તે તમારા ઇન્વૉઇસ પર નોંધાય.\nદરેક સમયગાળો એક વખતની ચુકવણી છે. કંઈ પણ આપમેળે રિન્યૂ થતું નથી.\nતમારા ઇન્વૉઇસ મારી ચુકવણીઓમાં છે.\nચુકવણી કરેલો સમયગાળો પૂરો થાય ત્યારે, આગલા સમયગાળાની ચુકવણી કરો ત્યાં સુધી તમારું ખાતું મફત પ્લાનની મર્યાદાઓ પર પાછું આવે છે."}$t$::jsonb, 40, false)
on conflict (slug) do nothing;

do $check$
begin
  if (select count(*) from public.faqs where surface = 'seller_help' and active) < 17 then
    raise exception 'the seller help FAQs are missing';
  end if;
  if (select count(*) from public.faqs where surface = 'buyer_help' and not active and translations <> '{}'::jsonb) < 7 then
    raise exception 'the MPF-14 drafts are missing';
  end if;
  if (select count(*) from public.help_guides
       where slug in ('complete-verification', 'request-a-callback', 'audio-pdf-image-support', 'payment-and-subscription')) <> 4 then
    raise exception 'the four Quick Guides are missing';
  end if;
  -- 27 of the 30 active rows matched the catalogues on 2026-10-01. The other three
  -- (Seller Registration answers written as bullet lists) keep the catalogue fallback.
  if (select count(*) from public.faqs where active and surface <> 'seller_help' and translations <> '{}'::jsonb) < 27 then
    raise exception 'the translation backfill matched fewer rows than the 27 measured';
  end if;
end
$check$;
