-- ═══════════════════════════════════════════════════════════════════════════
-- product-videos storage reconciliation
--
-- Run manually (Supabase SQL editor or MCP). Read-only by design — see the
-- bottom of this file for why the delete step is not automated.
--
-- WHY THIS EXISTS
-- deleteProductVideo() in src/lib/queries/videos.ts removes the storage objects
-- BEFORE the row, deliberately: the row is the only record of where the files
-- live, so the other order leaves an object nothing in the app can ever find
-- again. That covers the app's own delete path. It does not cover an admin
-- deleting a row with direct SQL, a failed insert after a successful upload, or
-- the tus-fingerprint case that produced a real 30 MB orphan once already
-- (resumableUpload's header comment has the full story).
--
-- These two queries are the two directions that can go wrong. Neither deletes
-- anything.
-- ═══════════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────────
-- QUERY 1 — Orphaned objects: bytes in the bucket that no row points at.
--
-- Matching is on the storage KEY, not the whole URL string: the key is the only
-- part that is stable (the project hostname is environment-dependent), and
-- split_part avoids LIKE, whose `_` and `%` would be wildcards inside a
-- filename. Keys generated by createProductVideo are `<vendor_id>/<ts>-<rand>.<ext>`
-- with no percent-encoding, so no URL-decoding step is needed.
--
-- THE AGE GUARD IS NOT OPTIONAL. createProductVideo uploads the video, then the
-- poster, then inserts the row — a multi-second window on a phone connection
-- during which the object legitimately exists with no row referencing it. Any
-- reconciliation that ignores that window will eventually delete a video
-- mid-upload. One hour is far longer than the widest plausible upload.
-- ───────────────────────────────────────────────────────────────────────────

with referenced as (
  -- provider = 'supabase' only: a Bunny URL split_parts to '' and would add a
  -- meaningless empty key to the set. Harmless here (nothing is named ''), but
  -- stated so the filter is not "cleaned up" out of Query 2, where the same
  -- behaviour IS harmful.
  select split_part(video_url, '/storage/v1/object/public/product-videos/', 2) as key
    from public.product_videos
   where provider = 'supabase' and video_url is not null
  union
  select split_part(thumbnail_url, '/storage/v1/object/public/product-videos/', 2)
    from public.product_videos
   where provider = 'supabase' and thumbnail_url is not null
)
select
  o.name                              as storage_key,
  o.created_at,
  pg_size_pretty((o.metadata->>'size')::bigint) as size,
  o.metadata->>'mimetype'             as mime,
  split_part(o.name, '/', 1)          as vendor_id_prefix
from storage.objects o
where o.bucket_id = 'product-videos'
  and o.created_at < now() - interval '1 hour'   -- upload-in-flight guard
  and not exists (select 1 from referenced r where r.key = o.name)
order by (o.metadata->>'size')::bigint desc nulls last;


-- ───────────────────────────────────────────────────────────────────────────
-- QUERY 2 — The other direction: rows pointing at objects that are gone.
--
-- A row here renders as a broken video (or a broken poster) in the buyer feed
-- and in the vendor's own list. Worth checking in the same pass, because the
-- failure modes that create orphans — a partial delete, a mis-recorded path —
-- tend to create these too.
-- ───────────────────────────────────────────────────────────────────────────

select
  v.id,
  v.vendor_id,
  v.status,
  v.created_at,
  case when v.video_url is null then null
       when exists (
         select 1 from storage.objects o
         where o.bucket_id = 'product-videos'
           and o.name = split_part(v.video_url, '/storage/v1/object/public/product-videos/', 2)
       ) then 'ok' else 'MISSING' end as video_object,
  case when v.thumbnail_url is null then null
       when exists (
         select 1 from storage.objects o
         where o.bucket_id = 'product-videos'
           and o.name = split_part(v.thumbnail_url, '/storage/v1/object/public/product-videos/', 2)
       ) then 'ok' else 'MISSING' end as thumb_object
from public.product_videos v
-- provider filter is LOAD-BEARING, not tidiness. split_part() returns an EMPTY
-- STRING (not null) when the delimiter is absent, so a Bunny playback URL
-- reduces to '' , matches no storage object, and would be reported as MISSING —
-- i.e. this query would declare the entire Bunny catalogue broken the first
-- time it ran after the migration. Bunny rows are Query 3's job.
where v.provider = 'supabase'
  and (v.video_url is not null or v.thumbnail_url is not null)
order by v.created_at desc;
-- Add `having`-style filtering by wrapping this in a subquery and keeping only
-- rows where either column = 'MISSING'; left unfiltered so a clean run still
-- shows you it actually checked something.


-- ═══════════════════════════════════════════════════════════════════════════
-- DELETING WHAT QUERY 1 FOUND — a human step, on purpose.
--
-- Not a cron job, and not an RPC that deletes. Two reasons:
--
-- 1. The race above is real and only mostly closed by the age guard. A resumed
--    tus upload can span far more than an hour of wall-clock time (that is the
--    entire point of resumable uploads), so an object with no row is not proof
--    of an orphan — only evidence worth a look.
-- 2. An orphan is 4 MB of storage on a plan measured in GB. A wrongly deleted
--    object is a vendor's video gone with no undo. The costs are not
--    symmetric, so the default must be "list it and let someone look."
--
-- To delete after reviewing, do it through the Storage API (the dashboard, or
-- supabase.storage.from('product-videos').remove([...])) rather than
-- `delete from storage.objects` — the SQL row is not the file, and deleting it
-- directly leaves the actual object behind in the backing store while removing
-- the only handle you had on it.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- QUERY 3 — the Bunny Stream half (provider='bunny' rows)
--
-- Everything above diffs storage.objects against product_videos, which works
-- only because both live in this database. Bunny does not, so the full diff
-- cannot be a query: listing a Bunny library needs the API key, and the API key
-- exists nowhere except the edge runtime. The Bunny-side diff is therefore the
-- `bunny-reconcile` edge function, which is admin-gated, read-only, and applies
-- the SAME one-hour age guard as Query 1 for the same reason — bunny-upload-url
-- creates the Bunny video BEFORE the client uploads a byte and before the row
-- is inserted, so a just-created video legitimately has no row for the whole
-- duration of an upload.
--
--   Run it as a super_admin or product_moderator:
--     supabase.functions.invoke("bunny-reconcile", { body: {} })
--   or from the repo:
--     node scripts/bunny-config-check.mjs   (checks configuration, not orphans)
--
-- What follows is the DATABASE side of that diff, useful on its own: it is the
-- list the function compares Bunny's library against. If this returns rows the
-- function says are missing at Bunny, those rows have broken playback right now
-- — in the buyer feed and in the moderation queue alike.
-- ═══════════════════════════════════════════════════════════════════════════

select
  v.id,
  v.vendor_id,
  v.status,
  v.created_at,
  v.bunny_video_id,
  v.video_url,
  -- A bunny row with no GUID should not exist: createProductVideo writes both
  -- together or neither. If this column ever reads 'MISSING GUID', the delete
  -- path cannot clean that row up and reconciliation cannot see it either.
  case when v.bunny_video_id is null then 'MISSING GUID' else 'ok' end as guid_state
from public.product_videos v
where v.provider = 'bunny'
order by v.created_at desc;


-- Provider census — the one-line answer to "has the migration actually
-- happened?". While Bunny is unconfigured, createProductVideo falls back to the
-- Supabase Storage path and every new row still says 'supabase'; that fallback
-- is deliberate and safe, but it is also silent, so this is how you notice.
select provider, count(*), min(created_at) as oldest, max(created_at) as newest
from public.product_videos
group by provider
order by provider;
